AWSTemplateFormatVersion: "2010-09-09"

Resources:
  
  LoadBalancerSecurityGP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: impex-23-lb-SecurityGP
      GroupDescription: Security group for load balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  
  ImpexLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: impex-23-alb
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !GetAtt LoadBalancerSecurityGP.GroupId

  ImpexTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: impex-23-targetgroup
      VpcId: !Ref VPC
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /
      TargetType: ip

  ImpexListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ImpexTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ImpexLoadBalancer
      Port: 80
      Protocol: HTTP