AWSTemplateFormatVersion: "2010-09-09"

Resources:
  
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: impex-23-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: impex-23-container
          Image: 266842636661.dkr.ecr.us-east-1.amazonaws.com/myapp4:v1
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - EC2
        - FARGATE

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: impex-23-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2   
          SecurityGroups:
            - !GetAtt SecurityGroupContainer.GroupId